# Generated by Django 5.1.6 on 2025-03-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paratabledata_master_grp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_data',
            name='parameter_name',
        ),
    ]
