# Generated by Django 5.1.6 on 2025-04-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_master_data_parameter_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementData',
        ),
    ]
