# Generated by Django 5.1.6 on 2025-04-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_measurementdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('parameter_name', models.CharField(max_length=100)),
                ('lsl', models.FloatField()),
                ('usl', models.FloatField()),
                ('ltl', models.FloatField()),
                ('utl', models.FloatField()),
                ('nominal', models.FloatField()),
                ('output', models.FloatField()),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('tir_value', models.FloatField()),
                ('statusCell', models.CharField(max_length=100)),
                ('overall_status', models.CharField(max_length=100)),
            ],
        ),
    ]
