# Generated by Django 5.1.6 on 2025-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_backupsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=255)),
                ('parameter_name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=10)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('part_model', 'parameter_name')},
            },
        ),
    ]
